name = "AdrenaFactory"
author = "SeaswimmerTheFsh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ce164e8f4c16585d48a2683411c792e24225a3e3251b4c8a124513917990f2"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
